### ISSUE TITLE
Feature Request:  Toolbar should be hidden

### ISSUE THREAD

**Issue by xshapira** [arnav-kr/json-formatter#10]
### Describe your feature

Seeing the toolbar every time you load the page is annoying and distracting. The toolbar should be hidden when the page loads and only display if the user chooses to toggle it on.

Thanks!

**Comment by arnav-kr** [comment]
Added in V2.0.3

Toolbar is now hidden by default.
further more, added other things too like there are now 60+ themes to choose from and few more options to configure.

The Extension is still not updated in webstore (in review) so keeping it open for now
will close when it gets public

**Comment by xshapira** [comment]
Thanks. Great job! @arnav-kr

**Comment by arnav-kr** [comment]
Published to webstore closing the issue

https://jsonformatter.page.link/chrome
