### ISSUE TITLE
Bug: Chrome native UI preventing JSON Formatter

### ISSUE THREAD

**Issue by tippold** [arnav-kr/json-formatter#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Chrome seems to have introduced a new feature called "pretty print" when opening JSON files. It seems that this is blocking the JSON formatter from working properly. The usual UI elements and formatting are not displayed.

Using Chrome version 117.0.5938.62

Your extension is the most convenient JSON formatter out there, so a fix would be very much appreciated. Thank you!

### Expected Behavior

JSON Files in browser are formatted and extension UI is displayed.

### Steps To Reproduce

1. Open JSON feed in browser
2. Top of page shows Chrome pretty print option
3. JSON is not formatted and extension not displayed in browser window

### System Info

```markdown
- OS: Mac OSX Ventura 13.5.2 (22G91)
- Browser: Version 117.0.5938.62
```

### Additional context?

![jsonfeed](https://github.com/arnav-kr/json-formatter/assets/38555636/e0abec89-e1ba-47c8-9e64-4270ada7bf67)

**Comment by tippold** [comment]
You're welcome! Thank you for reacting so quickly and for all of your continued efforts. Keep up the great work 😃

**Comment by arnav-kr** [comment]
@tippold The Extension is live on the webstore: https://jsonformatter.page.link/chrome
<img width="177" alt="image" src="https://github.com/arnav-kr/json-formatter/assets/72879799/eb90e79e-9082-42b8-879b-093102e77f1d">

chrome should auto update it
