### ISSUE TITLE
Question: Collapse/Exapnd All option

### ISSUE THREAD

**Issue by dev-thinks** [arnav-kr/json-formatter#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Question: I remember i used to use this feature a lot (Collapse/Exapnd All), but in the latest version am not able to see this option anymore. am missing something to get this option back?

please let me know.

### System Info

```markdown
- OS: Windows
- Browser: Version 118.0.5993.71 (Official Build) (64-bit)

```

**Comment by arnav-kr** [comment]
Its not there yet, will add as a feature request

**Comment by arnav-kr** [comment]
Implemented in v2.0.6, updates will be live when webstore review is complete
you can use right click context menu,
or use keyboard shortcuts
`[` - Collapse All
`]` - Expand All
[Webstore](https://chromewebstore.google.com/detail/json-formatter/gpmodmeblccallcadopbcoeoejepgpnb)

**Comment by IchHabRecht** [comment]
Hi @arnav-kr 

Will there be any update on the firefox webstore as well? And can you tell if the keys can be configured as there are keyboard layouts with uncomfortable brakets :-)

**Comment by arnav-kr** [comment]
> And can you tell if the keys can be configured as there are keyboard layouts with uncomfortable brakets :-)

Not yet, but thanks for pointing it out, i'll add it in the next update

> Will there be any update on the firefox webstore as well?

Ah, yeah it'd be, but porting the code is an overdue, as it was firstly written for chrome, and Firefox uses different namespace, I'll probably use the firefox-first approach and polyfilling for chrome, but that's for until I ship the custom keyboard shortcuts, then will be updated on the webstore, edge store and firefox at the same time,

For Now, I am opening an another issue to keep track of it there https://github.com/arnav-kr/json-formatter/issues/26

> [!NOTE]
for reference, the latest version is currently only available on the chrome webstore
