### ISSUE TITLE
Bug: Edge Browser Redirects to BreadcrumbList Instead of YouTube Video When Clicking External Links

### ISSUE THREAD

**Issue by LKSFerreira** [arnav-kr/json-formatter#19]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When clicking on external links that redirected me to a YouTube video using Edge as my default browser, instead of opening the video in question, the browser brought up a BreadcrumbList.

However, if you disable the automatic use of the extension, the problem is temporarily resolved, remembering that this did not happen a week ago.

### Expected Behavior

I was expecting a YouTube video to be played.

### Steps To Reproduce

1 - From an external application, such as Outlook, click on a link that should redirect you to play a video on YouTube using Edge as the default browser.

### System Info

```markdown
- OS: Windows 11 Pro 22H2 (22621.2428)
- Browser: Microsoft Edge Versão 117.0.2045.60 (Compilação oficial) (64 bits)
```

### Additional context?

![Imagem do WhatsApp de 2023-10-13 à(s) 15 36 29_e2ed8623](https://github.com/arnav-kr/json-formatter/assets/103146024/d096c58b-cc47-4ff9-af00-f54f5b0cad16)

**Comment by arnav-kr** [comment]
Fixed and Submitted for Edge Store/Webstore Approval, would be live there in sometime, i would notify you once its published

**Comment by arnav-kr** [comment]
@LKSFerreira its live on Edge Store

https://jsonformatter.page.link/edge

webstore: https://jsonformatter.page.link/chrome
