### ISSUE TITLE
Feature Request: Support running in iframes

### ISSUE THREAD

**Issue by andrewpollock** [arnav-kr/json-formatter#22]
### Describe your feature

I'd like for iframed JSON content to be formatted as well.

### Any Solutions You have thought of?

I believe this merely involves added

```
"all_frames": true
```

to the `content_scripts` array in https://github.com/arnav-kr/json-formatter/blob/main/extension/manifest.json

**Comment by arnav-kr** [comment]
Implemented in v2.0.6, updates will be live when webstore review is complete
[Webstore](https://chromewebstore.google.com/detail/json-formatter/gpmodmeblccallcadopbcoeoejepgpnb)
