### ISSUE TITLE
Bug: update prompt not going away

### ISSUE THREAD

**Issue by LoveSkylark** [arnav-kr/json-formatter#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is permanently pasted on my raw github pages:
<img width="334" alt="image" src="https://github.com/arnav-kr/json-formatter/assets/1541034/23b792d4-781b-478e-b114-7ee07b1c70da">

I've had to uninstall the extension so I can copy raw github pages into my notepad

### Expected Behavior

go away after displaying once

### Steps To Reproduce

open a raw json file on a github site like:
https://raw.githubusercontent.com/arnav-kr/json-formatter/main/extension/manifest.json

### System Info

```markdown
- OS:Windows-11
- Browser: Brave
```

**Comment by arnav-kr** [comment]
did you try clicking the close button
