### ISSUE TITLE
Feature Request: Ability to customize keyboard shortcuts

### ISSUE THREAD

**Issue by arnav-kr** [arnav-kr/json-formatter#26]
### Describe your feature

AN option to customize keyboard shortcuts in the json formatter options, that'd let a user modify key bindings to respective actions

### Additional context?

https://github.com/arnav-kr/json-formatter/issues/18#issuecomment-2204511880
@IchHabRecht

**Comment by IchHabRecht** [comment]
Thank you so much!

**Comment by arnav-kr** [comment]
Implemented in #27, actually I had forgotten to merge it to main
will be there in next webstore release
