### ISSUE TITLE
Feature Request: Text Overflow Wrapping with Option to Toggle On/Off

### ISSUE THREAD

**Issue by skeeith** [arnav-kr/json-formatter#3]
### Describe your feature

Currently the json formatter doesn't have support for `text overflow wrapping`, it would be nice if you could support this and add a toggle option to enable or disable `text overflow wrapping`.

### Any Solutions You have thought of?

add `text overflow wrapping`

### Additional context?

Cause what I see is, it's hard to copy paste long access token codes that goes way way way to the right of your screen where you have to scroll for a few seconds to reach the end, having an `text overflow wrapping` will make much easier for people who uses mouse.

FYI, I don't ever use mouse though, just suggestion a nice to have feature for this awesome plugin.

**Comment by arnav-kr** [comment]
Thanks for the feature request @skeeith, I see it as useful feature to have 🙂.
That is indeed easy to implement, but I was already working on next update and its still unfinished and I am planning to add this in that altogether while rolling out that one. And that gonna be cool with more customizable options and most awaited feature to change themes and yeah an easy to use UI for creating custom themes too and probably in future a small store of plugins too.
But sadly not getting much time from my daily routine to work on it and its still lying around unfinished. I would try to take out some time and finish it ASAP. 

Thanks For your Support as a contributor

Here are some sneak peaks for the next update that I have finished till now.

Not gonna reveal the theme builder now (its already finished tho)😉

Here goes the settings menu
<img width="336" alt="image" src="https://user-images.githubusercontent.com/72879799/192030267-48f5cbb4-ba4c-42dc-9ce3-59aa6466e669.png">

Theme Management page
<img width="345" alt="image" src="https://user-images.githubusercontent.com/72879799/192030389-4015e79a-b3d5-4eee-a2a7-5fd778e2b3b4.png">

A custom theme in preview (ik bad color choices tho lol):
<img width="960" alt="image" src="https://user-images.githubusercontent.com/72879799/192030622-b1f77114-d097-428c-94d3-8d8688f6200a.png">

**Comment by arnav-kr** [comment]
Added in V2.0.3

<img width="331" alt="image" src="https://user-images.githubusercontent.com/72879799/228239260-a679cc51-b226-4a6e-acc4-69c2cfcffd10.png">


now there is an option in extension settings to enable/disable word wrapping.
further more, added other things too like there are now 60+ themes to choose from and other stuff.

The Extension is still not updated in webstore (in review) so keeping it open for now
will close when it gets public
@skeeith

**Comment by arnav-kr** [comment]
Published to webstore closing the issue

https://jsonformatter.page.link/chrome
